receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed

  kafka:
    brokers:
      - agentops-kafka:29092
    traces:
      topic: agentops.telemetry.otlp.traces
      encoding: otlp_proto
    partition_traces_by_id: true
    

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, kafka]